version: "3.9"

services:
  browser:
    build: .
    volumes: 
      - /home/:/data
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DIRECTORY=/data
      # - SHOW_DOTFILES=false
      # - SHOW_DIRECTORY_SIZE=false
    